### ISSUE TITLE
[Nakamoto] signer keys must be associated with PoX addresses, not stackers

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-core#4290] opened 2024-01-25 15:21 UTC
Per https://github.com/stacks-network/stacks-core/discussions/4271 and #4269, the reward set needs to bind PoX addresses to signing keys in a many-to-many relationship:

* The reward set decides which signing keys act on behalf of a PoX address (with an associated "partial punishment" tactic for partial signer failures, described below)

* The reward set decides which PoX addresses a signing key can sign for.  A signing key failure would affect all its bound PoX addresses.

In the event that a PoX address has multiple signing keys, and some signing keys fail, then we deduct the proportional rewards by doing this:

> Right now, the idea is to have PoX payouts to the address cease if the associated signing key has failed to produce a signature for K Bitcoin blocks, and resume if they have resumed signing for K Bitcoin blocks. Are you thinking that instead of stopping the payout altogether, we flip a weighted coin (e.g. using the VRF) on PoX payouts to the offending address such that the probability of the payout being forfeited is proportional to the fraction of STX represented by the misbehaving signing keys?

**Comment by setzeus** [comment] 2024-02-02 13:09
Resurface during unblock, the problem is clear but requirements for Clarity / associated PoX-4 contracts a bit unclear.

**Comment by kantai** [comment] 2024-02-03 12:55
This relationship is already implemented in next. The only requirements for PoX-4 not implemented are that signing keys need to approve any request that sets the signing key. This is captured in #4247 and implemented by https://github.com/stacks-network/stacks-core/pull/4277

**Comment by hstove** [comment] 2024-02-09 01:20
Closed via #4277

**Closed** 2024-02-09 01:20 UTC
Labels: clarity, PoX-4, nakamoto, argon3.0
